CREATE TABLE Billett
(
    id INTEGER AUTO_INCREMENT NOT NULL,
    film VARCHAR(50) NOT NULL,
    antall VARCHAR(10) NOT NULL,
    fornavn VARCHAR(100) NOT NULL,
    etternavn VARCHAR(100) NOT NULL,
    telefonnr VARCHAR(50) NOT NULL,
    epost VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);